name: CD for Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release_and_docker:
    uses: ./.github/workflows/shared-cd-steps.yml
    with:
      version_file: config.ini
      dockerfile: devops/build/DockerfileK8S
