name: CD for Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release_and_docker:
    uses: ./.github/workflows/shared-cd-steps.yml
    with:
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      version_file: config.ini
      dockerfile: devops/build/DockerfileK8S
