name: CD for Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release_and_docker:
    uses: ./.github/workflows/shared-cd-steps.yml
    with:
      version_file: config.ini
      dockerfile: devops/build/DockerfileK8S
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}