name: CD

on:
  workflow_dispatch:

jobs:
  push_to_docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display structure of downloaded files
        uses: actions/download-artifact@v4
      - run: ls -R

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: tone-track-service-*

      - name: Load Docker image
        run: docker load -i tone-track-service.tar

      - name: Get version from config file
        id: get_version
        run: |
          VERSION=$(grep '^version' config.ini | sed 's/version = //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Tag Docker image with version and latest
        run: |
          docker tag "${{ env.DOCKER_USERNAME }}/tone-track-service:ci-${{ github.sha }}" "${{ env.DOCKER_USERNAME }}/tone-track-service:${{ env.VERSION }}"
          docker tag "${{ env.DOCKER_USERNAME }}/tone-track-service:ci-${{ github.sha }}" "${{ env.DOCKER_USERNAME }}/tone-track-service:latest"

      - name: Push Docker image with version tag
        run: docker push "${{ env.DOCKER_USERNAME }}/tone-track-service:${{ env.VERSION }}"

      - name: Push Docker image with "latest" tag
        run: docker push "${{ env.DOCKER_USERNAME }}/tone-track-service:latest"
