name: CI

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.12.2
      API_KEY: ${{ secrets.API_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 download_nltk_data.py

      - name: Run tests
        run: pytest tests/unittest

      - name: Log in to Docker Hub
        if: ${{ success() }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        if: ${{ success() }}
        run: docker build -t "${{ env.DOCKER_USERNAME }}/tone-track-service:ci-${{ github.sha }}" -f devops/build/Dockerfile .

      - name: Save Docker image as tar file
        run: docker save "${{ env.DOCKER_USERNAME }}/tone-track-service:ci-${{ github.sha }}" -o tone-track-service.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tone-track-service
          path: tone-track-service.tar
