name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.12.2
      PIP_CACHE_DIR: ~/.cache/pip
      API_KEY: ${{ secrets.API_KEY }}
      TF_ENABLE_ONEDNN_OPTS: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in the tts folder
        id: check_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- tts/; then
            echo "No changes in the tts folder."
            echo "::set-output name=skip_job::true"
          else
            echo "Changes detected in the tts folder."
            echo "::set-output name=skip_job::false"
          fi

      - name: Set up Python
        if: steps.check_changes.outputs.skip_job == 'false'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        if: steps.check_changes.outputs.skip_job == 'false'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --cache-dir ${{ env.PIP_CACHE_DIR }}
          python3 download_nltk_data.py

      - name: Run tests
        if: steps.check_changes.outputs.skip_job == 'false'
        run: |
          pytest tests/unittest
