name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.12.2
      PIP_CACHE_DIR: ~/.cache/pip
      API_KEY: ${{ secrets.API_KEY }}
      TF_ENABLE_ONEDNN_OPTS: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in the tts folder
        id: check_changes
        run: |
          git fetch origin master --depth=1
          if git diff --quiet origin/master HEAD -- tts/; then
            echo "No changes in the tts folder."
            echo "skip_job=true" >> $GITHUB_ENV
          else
            echo "Changes detected in the tts folder."
            echo "skip_job=false" >> $GITHUB_ENV
          fi

      - name: Set up Python
        if: env.skip_job == 'false'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        if: env.skip_job == 'false'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --cache-dir ${{ env.PIP_CACHE_DIR }}
          python3 download_nltk_data.py

      - name: Run tests
        if: env.skip_job == 'false'
        run: |
          pytest tests/unittest
