name: CRON UI TESTS

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/shared-cron-steps.yml
    with:
      python_version: "3.12.2"
      pip_cache_dir: ~/.cache/pip
      test_path: tests/ui
      report_name: ui-test-report
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
