name: CRON API TESTS

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  test:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/shared-cron-steps.yml
    with:
      python_version: "3.12.2"
      pip_cache_dir: ~/.cache/pip
      test_path: tests/api
      report_name: api-test-report
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
