name: CRON A11Y TESTS

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/shared-cron-steps.yml
    with:
      python_version: "3.12.2"
      pip_cache_dir: ~/.cache/pip
      test_path: tests/accessibility
      report_name: a11y-test-report
    secrets: inherit
