name: Common Steps

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      pip_cache_dir:
        required: true
        type: string
      test_path:
        required: true
        type: string
      report_name:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --cache-dir ${{ inputs.pip_cache_dir }}
          playwright install

      - name: Run tests
        run: |
          pytest ${{ inputs.test_path }}

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.report_name }}
          path: report.html
          retention-days: 1
